# project.yml file for 7M LCP
{
  # Driver section configures a modbus slave
  drivers: {
    mbslave: {
      uri: "../../modbus.async",
      config: {
        type: "serial.slave",
        timeout: 2000,
        mode: "ascii",
        serial_port: {
          port_name: !!vy/env LCP_PORT_ENV:COM11,
          port_options: {
              baudrate: 9600
          }
        },
        blocks: {
          4x: {
            slave_addr: 1,
            num_reg: 6,
            timeout: 5000
          }
        }
      }
    }
  },
  
  tags: {
    "1STWCKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.0" }
    },
    "2STWCKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.1" }
    },
    "3STWCKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.2" }
    },
    "4STWCKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.3" }
    },
    "CENTRAL.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.4" }
    },
    "SG1N.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.5" }
    },
    "SG2N.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.6" }
    },
    "SG1S.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.7" }
    },
    "SG2S.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.8" }
    },
    "SG3N.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.9" }
    },
    "SG3S.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.10" }
    },
    "SG4N.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.11" }
    },
    "SW12.REV.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.12" }
    },
    "SW12.NOR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.13" }
    },
    "SW12.LK.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.14" }
    },
    "SW21.REV.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:0.15" }
    },
    "SW21.NOR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.0" }
    },
    "SW21.LK.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.1" }
    },
    "SW34.REV.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.2" }
    },
    "SW34.NOR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.3" }
    },
    "SW34.LK.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.4" }
    },
    "SG4S.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.5" }
    },
    "SG1S.TL.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.6" }
    },
    "SG2S.TL.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.7" }
    },
    "P1-INHIBIT.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.8" }
    },
    "P2-INHIBIT.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.9" }
    },
    "SW43.REV.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.10" }
    },
    "SW43.NOR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.11" }
    },
    "SW43.LK.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.12" }
    },
    "1TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.13" }
    },
    "2TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.14" }
    },
    "3TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:1.15" }
    },
    "4TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.0" }
    },
    "6TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.1" }
    },
    "TF1.NORTH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.2" }
    },
    "TF1.SOUTH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.3" }
    },
    "TT2-INHIBIT.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.4" }
    },
    "TF2.NORTH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.5" }
    },
    "TF2.SOUTH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.6" }
    },
    "SPARE-IN2-I7": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.7" }
    },
    "7TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.8" }
    },
    "11TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.9" }
    },
    "12TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.10" }
    },
    "13TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.11" }
    },
    "14TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.12" }
    },
    "15TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.13" }
    },
    "16TKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.14" }
    },
    "TMODE.2.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:2.15" }
    },
    "TMODE.1.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.0" }
    },
    "SG5N.CLEAR.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.1" }
    },
    "SG5N.INH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.2" }
    },
    "13ATKE.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.3" }
    },
    "LOCAL.LCP.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.8" }
    },
    "LOCAL.BOOTH.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.14" }
    },
    "LOCAL.TCC.IND": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:3.15" }
    },
    "PLCOK.IND": {
        defaultValue: 0,
        driverinfo: { id: "sys", item: "driver.mbslave.online" }
    },
    "SG5N.INH.SET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.0" }
    },
    "SG5N.INH.RESET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.1" }
    },
    "TMODE.1.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.2" }
    },
    "TMODE.2.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.3" }
    },
    "SW12.REV.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.4" }
    },
    "SW12.NOR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.5" }
    },
    "SG1N.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.6" }
    },
    "SG1S.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.6" }
    },
   "SG1N.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.7" }
    },
    "SG1S.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.8" }
    },
    "SW21.REV.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.9" }
    },
    "SW21.NOR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.10" }
    },
    "SG2N.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.11" }
    },
    "SG2S.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.11" }
    },
    "SG2N.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.12" }
    },
    "SG2S.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.13" }
    },
    "SW34.REV.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.14" }
    },
    "SW34.NOR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:4.15" }
    },
    "SG3N.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.0" }
    },
    "SG3S.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.0" }
    },
    "SG3N.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.1" }
    },
    "SG3S.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.2" }
    },
    "SW43.REV.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.3" }
    },
    "SW43.NOR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.4" }
    },
    "SG4S.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.5" }
    },
    "SG4N.STOP.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.5" }
    },
    "SG4N.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.6" }
    },
    "SG4S.CLEAR.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.7" }
    },
    "SG1S.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.8" }
    },
    "SG2S.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.9" }
    },
    "SG3S.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.10" }
    },
    "SG4S.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.11" }
    },
    "SG1N.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.8" }
    },
    "SG2N.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.9" }
    },
    "SG3N.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.10" }
    },
    "SG4N.CALLON.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.11" }
    },
    "P1-INHIBIT.SET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.12" }
    },
    "P1-INHIBIT.RESET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.13" }
    },
    "P2-INHIBIT.RESET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.13" }
    },
    "TT2-INHIBIT.RESET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.13" }
    },
    "P1-INHIBIT.SET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.14" }
    },
    "TT2-INHIBIT.SET.CTL": {
        defaultValue: 0,
        driverinfo: { id: "mbslave", item: "4x@n:5.15" }
    }
  }
}